const actionTypes = {
  GET_CARDS_SAGA: 'GET_CARDS_SAGA',
  GET_CARDS: 'GET_CARDS',
  GET_CARD_INFO_SAGA: 'GET_CARD_INFO_SAGA',
  GET_CARD_INFO: 'GET_CARD_INFO',
  ADD_CARD_SAGA: 'ADD_CARD_SAGA',
  ADD_CARD: 'ADD_CARD',
  UPDATE_CARD_SAGA: 'UPDATE_CARD_SAGA',
  UPDATE_CARD: 'UPDATE_CARD',
  DEL_CARD_SAGA: 'DEL_CARD_SAGA',
  DEL_CARD: 'DEL_CARD',
  LIKE_CARD_SAGA: 'LIKE_CARD_SAGA',
  LIKE_CARD: 'LIKE_CARD',

  SIGNUP_SAGA: 'SIGNUP_SAGA',
  SIGNUP_AUTH: 'SIGNUP_AUTH',
  LOGIN_SAGA: 'LOGIN_SAGA',
  LOGIN_AUTH: 'LOGIN_AUTH',
  LOGOUT_AUTH: 'LOGOUT_AUTH'
};

export default actionTypes;
